# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch


# Create random tensor
t1 = torch.rand(7, 7)
t1


tensor([[0.9923, 0.7376, 0.7252, 0.5093, 0.7138, 0.4050, 0.4579],
        [0.6594, 0.8910, 0.9579, 0.3801, 0.3471, 0.4192, 0.3281],
        [0.7887, 0.9923, 0.4291, 0.6531, 0.6504, 0.9846, 0.2874],
        [0.1825, 0.1713, 0.5560, 0.9992, 0.3755, 0.9443, 0.5231],
        [0.3203, 0.7242, 0.8753, 0.6839, 0.4930, 0.3733, 0.3900],
        [0.5738, 0.4993, 0.9193, 0.5384, 0.7413, 0.5668, 0.8406],
        [0.1449, 0.0305, 0.8246, 0.9313, 0.6956, 0.0840, 0.9551]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
t2 = torch.rand(1, 7)

# Perform matrix multiplication
t3 = torch.matmul(t1, t2.T)
t3


tensor([[1.4237],
        [1.7639],
        [1.7668],
        [1.7209],
        [2.2455],
        [1.4379],
        [1.2856]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
t1 = torch.rand(7, 7)
t2 = torch.rand(1, 7)


# Matrix multiply tensors
t3 = t1 @ t2.T
t3


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
torch.cuda.is_available()


# Create two random tensors on GPU
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)
t1.device

device(type='cpu')

In [11]:
t2.device

device(type='cpu')

In [12]:
device = "cuda" if torch.cuda.is_available() else 'cpu'
t1.to(device)
t2.to(device)

tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')

In [14]:
t1

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
t3 = t1 @ t2.T
t3

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
print(torch.max(t3))

# Find min
print(torch.min(t3))

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max

print(t3.argmax())


# Find arg min
print(t3.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
# Set seed
torch.manual_seed(7)


# Create random tensor
t4 = torch.rand(1, 1, 1, 10)
print(t4)
print(t4.shape)


# Remove single dimensions
t4_squeezed = torch.squeeze(t4)
print(t4_squeezed.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
torch.Size([10])
